# Loan Data from Prosper
by Yara Aldajjani

## Contents:

## Introduction 
This dataset is financial dataset and this is related to the loan, borrowers, lenders, interest rates and stuffs like that. Prosper or Prosper Marketplace Inc. is a San Francisco, California based company specializing in loans at low interest rates to the borrowers. In this dataset, we are using the data from the Posper to analyse it and trying to find the pattern in the Prosper data. This may be tedious because of the sheer size of the dataset and the complicated nature of all the financial datasets.
We are using R, an advanced high level programming language of the analysis with some of its most popular graphic package ggplot. The codes are not visible in the HTML/PDF export for the simlicity but the codes can be reviewed from the RMD file.

The dataset is comprised of 81 variables and contains 113937 entries. The variable that are explored in the dataset are the following Term : Amount of month customers opted for loan

In [1]:
# Download the needed libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Data Wrangling 
### Data Gathering 
The dataset contains 113,937 loans with 81 variables on each loan, such as borrower rate (or interest rate), loan amount and so on.

In [2]:
# Loading the loans dataset
Loan_Data = pd.read_csv('prosperLoanData.csv')

In [3]:
# Load the loans dataset's dictionary 
Loan_Data_Dict= pd.read_csv('ProsperLoanDataDictionary.csv')

<br><br><br>
### Data Assessment
**Visual Assessment**:<br><br>
**Loan_Data**:

In [4]:
# To print all the columns in order to have a better look for the visual assessment
pd.set_option('display.max_columns', None)

In [5]:
# To prevent the characters truncation 
pd.set_option('max_colwidth', None)

In [6]:
Loan_Data

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperRating (Alpha),ProsperScore,ListingCategory (numeric),BorrowerState,Occupation,EmploymentStatus,EmploymentStatusDuration,IsBorrowerHomeowner,CurrentlyInGroup,GroupKey,DateCreditPulled,CreditScoreRangeLower,CreditScoreRangeUpper,FirstRecordedCreditLine,CurrentCreditLines,OpenCreditLines,TotalCreditLinespast7years,OpenRevolvingAccounts,OpenRevolvingMonthlyPayment,InquiriesLast6Months,TotalInquiries,CurrentDelinquencies,AmountDelinquent,DelinquenciesLast7Years,PublicRecordsLast10Years,PublicRecordsLast12Months,RevolvingCreditBalance,BankcardUtilization,AvailableBankcardCredit,TotalTrades,TradesNeverDelinquent (percentage),TradesOpenedLast6Months,DebtToIncomeRatio,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanKey,TotalProsperLoans,TotalProsperPaymentsBilled,OnTimeProsperPayments,ProsperPaymentsLessThanOneMonthLate,ProsperPaymentsOneMonthPlusLate,ProsperPrincipalBorrowed,ProsperPrincipalOutstanding,ScorexChangeAtTimeOfListing,LoanCurrentDaysDelinquent,LoanFirstDefaultedCycleNumber,LoanMonthsSinceOrigination,LoanNumber,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MemberKey,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_InterestandFees,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
0,1021339766868145413AB3B,193129,2007-08-26 19:09:29.263000000,C,36,Completed,2009-08-14 00:00:00,0.16516,0.1580,0.1380,NaN,NaN,NaN,NaN,NaN,NaN,0,CO,Other,Self-employed,2.0,True,True,NaN,2007-08-26 18:41:46.780000000,640.0,659.0,2001-10-11 00:00:00,5.0,4.0,12.0,1,24.0,3.0,3.0,2.0,472.0,4.0,0.0,0.0,0.0,0.00,1500.0,11.0,0.81,0.0,0.17,"$25,000-49,999",True,3083.333333,E33A3400205839220442E84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,78,19141,9425,2007-09-12 00:00:00,Q3 2007,1F3E3376408759268057EDA,330.43,11396.1400,9425.00,1971.1400,-133.18,0.0,0.0,0.0,0.0,1.0,0,0,0.0,258
1,10273602499503308B223C1,1209647,2014-02-27 08:28:07.900000000,NaN,36,Current,NaN,0.12016,0.0920,0.0820,0.07960,0.0249,0.05470,6.0,A,7.0,2,CO,Professional,Employed,44.0,False,False,NaN,2014-02-27 08:28:14,680.0,699.0,1996-03-18 00:00:00,14.0,14.0,29.0,13,389.0,3.0,5.0,0.0,0.0,0.0,1.0,0.0,3989.0,0.21,10266.0,29.0,1.00,2.0,0.18,"$50,000-74,999",True,6125.000000,9E3B37071505919926B1D82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,134815,10000,2014-03-03 00:00:00,Q1 2014,1D13370546739025387B2F4,318.93,0.0000,0.00,0.0000,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
2,0EE9337825851032864889A,81716,2007-01-05 15:00:47.090000000,HR,36,Completed,2009-12-17 00:00:00,0.28269,0.2750,0.2400,NaN,NaN,NaN,NaN,NaN,NaN,0,GA,Other,Not available,NaN,False,True,783C3371218786870A73D20,2007-01-02 14:09:10.060000000,480.0,499.0,2002-07-27 00:00:00,NaN,NaN,3.0,0,0.0,0.0,1.0,1.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.06,Not displayed,True,2083.333333,6954337960046817851BCB2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,86,6466,3001,2007-01-17 00:00:00,Q1 2007,5F7033715035555618FA612,123.32,4186.6300,3001.00,1185.6300,-24.20,0.0,0.0,0.0,0.0,1.0,0,0,0.0,41
3,0EF5356002482715299901A,658116,2012-10-22 11:02:35.010000000,NaN,36,Current,NaN,0.12528,0.0974,0.0874,0.08490,0.0249,0.06000,6.0,A,9.0,16,GA,Skilled Labor,Employed,113.0,True,False,NaN,2012-10-22 11:02:32,800.0,819.0,1983-02-28 00:00:00,5.0,5.0,29.0,7,115.0,0.0,1.0,4.0,10056.0,14.0,0.0,0.0,1444.0,0.04,30754.0,26.0,0.76,0.0,0.15,"$25,000-49,999",True,2875.000000,A0393664465886295619C51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,16,77296,10000,2012-11-01 00:00:00,Q4 2012,9ADE356069835475068C6D2,321.45,5143.2000,4091.09,1052.1100,-108.01,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
4,0F023589499656230C5E3E2,909464,2013-09-14 18:38:39.097000000,NaN,36,Current,NaN,0.24614,0.2085,0.1985,0.18316,0.0925,0.09066,3.0,D,4.0,2,MN,Executive,Employed,44.0,True,False,NaN,2013-09-14 18:38:44,680.0,699.0,2004-02-20 00:00:00,19.0,19.0,49.0,6,220.0,1.0,9.0,0.0,0.0,0.0,0.0,0.0,6193.0,0.81,695.0,39.0,0.95,2.0,0.26,"$100,000+",True,9583.333333,A180369302188889200689E,1.0,11.0,11.0,0.0,0.0,11000.0,9947.90,NaN,0,NaN,6,102670,15000,2013-09-20 00:00:00,Q3 2013,36CE356043264555721F06C,563.97,2819.8500,1563.22,1256.6300,-60.27,0.0,0.0,0.0,0.0,1.0,0,0,0.0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113932,E6D9357655724827169606C,753087,2013-04-14 05:55:02.663000000,NaN,36,Current,NaN,0.22354,0.1864,0.1764,0.16490,0.0699,0.09500,4.0,C,5.0,1,IL,Food Service Management,Employed,246.0,True,False,NaN,2013-04-14 05:54:58,700.0,719.0,1997-09-01 00:00:00,9.0,9.0,41.0,9,209.0,0.0,0.0,0.0,0.0,7.0,1.0,0.0,7714.0,0.80,1886.0,37.0,0.83,3.0,0.13,"$50,000-74,999",True,4333.333333,9BD7367919051593140DB62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,11,88485,10000,2013-04-22 00:00:00,Q2 2013,2EC435768441332602FDC15,364.74,3647.4000,2238.38,1409.0200,-75.58,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
113933,E6DB353036033497292EE43,537216,2011-11-03 20:42:55.333000000,NaN,36,FinalPaymentInProgress,NaN,0.13220,0.1110,0.1010,0.10070,0.0200,0.08070,6.0,A,8.0,7,PA,Professional,Employed,21.0,True,False,NaN,2011-11-03 20:42:53,700.0,719.0,1992-01-17 00:00:00,14.0,13.0,39.0,9,495.0,1.0,4.0,1.0,5062.0,4.0,0.0,0.0,15743.0,0.69,6658.0,39.0,0.92,0.0,0.11,"$75,000-99,999",True,8041.666667,62D93634569816897D5A276,3.0,60.0,60.0,0.0,0.0,33501.0,4815.42,-26.0,0,NaN,28,55801,2000,2011-11-07 00:00:00,Q4 2011,55C4336679182766893E4FC,65.57,2330.5500,1997.16,333.3900,-30.05,0.0,0.0,0.0,0.0,1.0,0,0,0.0,22
113934,E6E13596170052029692BB1,1069178,2013-12-13 05:49:12.703000000,NaN,60,Current,NaN,0.23984,0.2150,0.2050,0.18828,0.1025,0.08578,3.0,D,3.0,1,TX,Other,Employed,84.0,True,False,NaN,2013-12-13 05:49:15,700.0,719.0,2002-02-25 00:00:00,12.0,12.0,25.0,9,521.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,22147.0,0.73,7853.0,25.0,1.00,0.0,0.51,"$25,000-49,999",True,2875.000000,DD1A370200396006300ACA0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,3,123122,10000,2013-12-23 00:00:00,Q4 2013,0FE0370029359765342FDB5,273.35,546.7000,183.15,363.5500,-16.91,0.0,0.0,0.0,0.0,1.0,0,0,0.0,119
113935,E6EB3531504622671970D9E,539056,2011-11-14 13:18:26.597000000,NaN,60,Completed,2013-08-13 00:00:00,0.28408,0.2605,0.2505,0.24450,0.0850,0.15950,4.0,C,5.0,2,GA,Food Service,Full-time,94.0,True,False,NaN,2011-11-14 13:18:24,680.0,699.0,1993-12-01 00:00:00,11.0,11.0,22.0,7,488.0,1.0,4.0,0.0,0.0,0.0,1.0,0.0,11956.0,0.69,4137.0,19.0,0.80,1.0,0.48,"$25,000-49,999",True,3875.000000,589536350469116027ED11B,1.0,16.0,16.0,0.0,0.0,5000.0,3264.37,-4.0,0,NaN,28,56401,15000,2011-11-21 00:00:00,Q4 2011,A33834861822272782621C8,449.55,21122.5600,15000.00,6122.5600,-235.05,0.0,0.0,0.0,0.0,1.0,0,0,0.0,274
113936,E6ED3600409833199F711B7,1140093,2014-01-15 09:27:37.657000000,NaN,36,Current,NaN,0.13189,0.1039,0.0939,0.09071,0.0299,0.06081,6.0,A,7.0,1,NY,Professor,Employed,244.0,False,False,NaN,2014-01-15 09:27:40,680.0,699.0,1995-01-01 00:00:00,10.0,9.0,44.0,8,289.0,0.0,1.0,1.0,257.0,3.0,1.0,0.0,6166.0,0.80,675.0,36.0,0.75,0.0,0.23,"$50,000-74,999",True,4583.333333,00AF3704550953269A64E40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,2,127508,2000,2014-01-21 00:00:00,Q1 2014,CE1E3704648000761C9F724,64.90,64.3307,47.25,17.0807,-1.70,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1

<br><br>
**Loan_Data_Dict**:

In [7]:
# To print all the rows in order to have a better look for the visual assessment
pd.set_option("max_rows", None)

In [8]:
Loan_Data_Dict

,Variable,Description
0,ListingKey,"Unique key for each listing, same value as the 'key' used in the listing object in the API."
1,ListingNumber,The number that uniquely identifies the listing to the public as displayed on the website.
2,ListingCreationDate,The date the listing was created.
3,CreditGrade,The Credit rating that was assigned at the time the listing went live. Applicable for listings pre-2009 period and will only be populated for those listings.
4,Term,The length of the loan expressed in months.
5,LoanStatus,"The current status of the loan: Cancelled, Chargedoff, Completed, Current, Defaulted, FinalPaymentInProgress, PastDue. The PastDue status will be accompanied by a delinquency bucket."
6,ClosedDate,"Closed date is applicable for Cancelled, Completed, Chargedoff and Defaulted loan statuses."
7,BorrowerAPR,The Borrower's Annual Percentage Rate (APR) for the loan.
8,BorrowerRate,The Borrower's interest rate for this loan.
9,LenderYield,The Lender yield on the loan. Lender yield is equal to the interest rate on the loan less the servicing fee.
10,EstimatedEffectiveYield,"Effective yield is equal to the borrower interest rate (i) minus the servicing fee rate, (ii) minus estimated uncollected interest on charge-offs, (iii) plus estimated collected late fees. Applicable for loans originated after July 2009."
11,EstimatedLoss,Estimated loss is the estimated principal loss on charge-offs. Applicable for loans originated after July 2009.
12,EstimatedReturn,The estimated return assigned to the listing at the time it was created. Estimated return is the difference between the Estimated Effective Yield and the Estimated Loss Rate. Applicable for loans originated after July 2009.
13,ProsperRating (numeric),"The Prosper Rating assigned at the time the listing was created: 0 - N/A, 1 - HR, 2 - E, 3 - D, 4 - C, 5 - B, 6 - A, 7 - AA. Applicable for loans originated after July 2009."
14,ProsperRating (Alpha),The Prosper Rating assigned at the time the listing was created between AA - HR. Applicable for loans originated after July 2009.
15,ProsperScore,"A custom risk score built using historical Prosper data. The score ranges from 1-10, with 10 being the best, or lowest risk score. Applicable for loans originated after July 2009."
16,ListingCategory,"The category of the listing that the borrower selected when posting their listing: 0 - Not Available, 1 - Debt Consolidation, 2 - Home Improvement, 3 - Business, 4 - Personal Loan, 5 - Student Use, 6 - Auto, 7- Other, 8 - Baby&Adoption, 9 - Boat, 10 - Cosmetic Procedure, 11 - Engagement Ring, 12 - Green Loans, 13 - Household Expenses, 14 - Large Purchases, 15 - Medical/Dental, 16 - Motorcycle, 17 - RV, 18 - Taxes, 19 - Vacation, 20 - Wedding Loans"
17,BorrowerState,The two letter abbreviation of the state of the address of the borrower at the time the Listing was created.
18,Occupation,The Occupation selected by the Borrower at the time they created the listing.
19,EmploymentStatus,The employment status of the borrower at the time they posted the listing.
20,EmploymentStatusDuration,The length in months of the employment status at the time the listing was created.
21,IsBorrowerHomeowner,A Borrower will be classified as a homowner if they have a mortgage on their credit profile or provide documentation confirming they are a homeowner.
22,CurrentlyInGroup,Specifies whether or not the Borrower was in a group at the time the listing was created.
23,GroupKey,The Key of the group in which the Borrower is a member of. Value will be null if the borrower does not have a group affiliation.
24,DateCreditPulled,The date the credit profile was pulled.
25,CreditScoreRangeLower,The lower value representing the range of the borrower's credit score as provided by a consumer credit rating agency.
26,CreditScoreRangeUpper,The upper value representing the range of the borrower's credit score as provided by a consumer credit rating agency.
27,FirstRecordedCreditLine,The date the first credit line was opened.
28,CurrentCreditLines,Number of current credit lines at the time the credit profile was pulled.
29,OpenCreditLines,Number of open credit lines at the time the credit profile was pulled.
30,TotalCreditLinespast7years,Number of credit lines in the past seven years at the time the credit profile was pulled.
31,OpenRevolvingAccounts,Number of open revolving accounts at the time the credit profile was pulled.
32,OpenRevolvingMonthlyPayment,Monthly payment on revolving accounts at the time the credit profile was pulled.
33,InquiriesLast6Months,Number of inquiries in the past six months at the time the credit profile was pulled.
34,TotalInquiries,Total number of inquiries at the time the credit profile was pulled.
35,CurrentDelinquencies,Number of accounts delinquent at the time the credit profile was pulled.
36,AmountDelinquent,Dollars delinquent at the time the credit profile was pulled.
37,DelinquenciesLast7Years,Number of delinquencies in the past 7 years at the time the credit profile was pulled.
38,PublicRecordsLast10Years,Number of public records in the past 10 years at the time the credit profile was pulled.
39,PublicRecordsLast12Months,Number of public records in the past 12 months at the time the credit profile was pulled.
40,RevolvingCreditBalance,Dollars of revolving credit at the time the credit profile was pulled.
41,BankcardUtilization,The percentage of available revolving credit that is utilized at the time the credit profile was pulled.
42,AvailableBankcardCredit,The total available credit via bank card at the time the credit profile was pulled.
43,TotalTrades,Number of trade lines ever opened at the time the credit profile was pulled.
44,TradesNeverDelinquent,Number of trades that have never been delinquent at the time the credit profile was pulled.
45,TradesOpenedLast6Months,Number of trades opened in the last 6 months at the time the credit profile was pulled.
46,DebtToIncomeRatio,The debt to income ratio of the borrower at the time the credit profile was pulled. This value is Null if the debt to income ratio is not available. This value is capped at 10.01 (any debt to income ratio larger than 1000% will be returned as 1001%).
47,IncomeRange,The income range of the borrower at the time the listing was created.
48,IncomeVerifiable,The borrower indicated they have the required documentation to support their income.
49,StatedMonthlyIncome,The monthly income the borrower stated at the time the listing was created.
50,LoanKey,Unique key for each loan. This is the same key that is used in the API.
51,TotalProsperLoans,Number of Prosper loans the borrower at the time they created this listing. This value will be null if the borrower had no prior loans.
52,TotalProsperPaymentsBilled,Number of on time payments the borrower made on Prosper loans at the time they created this listing. This value will be null if the borrower had no prior loans.
53,OnTimeProsperPayments,Number of on time payments the borrower had made on Prosper loans at the time they created this listing. This value will be null if the borrower has no prior loans.
54,ProsperPaymentsLessThanOneMonthLate,Number of payments the borrower made on Prosper loans that were less than one month late at the time they created this listing. This value will be null if the borrower had no prior loans.
55,ProsperPaymentsOneMonthPlusLate,Number of payments the borrower made on Prosper loans that were greater than one month late at the time they created this listing. This value will be null if the borrower had no prior loans.
56,ProsperPrincipalBorrowed,Total principal borrowed on Prosper loans at the time the listing was created. This value will be null if the borrower had no prior loans.
57,ProsperPrincipalOutstanding,Principal outstanding on Prosper loans at the time the listing was created. This value will be null if the borrower had no prior loans.
58,ScorexChangeAtTimeOfListing,Borrower's credit score change at the time the credit profile was pulled. This will be the change relative to the borrower's last Prosper loan. This value will be null if the borrower had no prior loans.
59,LoanCurrentDaysDelinquent,The number of days delinquent.
60,LoanFirstDefaultedCycleNumber,The cycle the loan was charged off. If the loan has not charged off the value will be null.
61,LoanMonthsSinceOrigination,Number of months since the loan originated.
62,LoanNumber,Unique numeric value associated with the loan.
63,LoanOriginalAmount,The origination amount of the loan.
64,LoanOriginationDate,The date the loan was originated.
65,LoanOriginationQuarter,The quarter in which the loan was originated.
66,MemberKey,The unique key that is associated with the borrower. This is the same identifier that is used in the API member object.
67,MonthlyLoanPayment,The scheduled monthly loan payment.
68,LP_CustomerPayments,"Pre charge-off cumulative gross payments made by the borrower on the loan. If the loan has charged off, this value will exclude any recoveries."
69,LP_CustomerPrincipalPayments,"Pre charge-off cumulative principal payments made by the borrower on the loan. If the loan has charged off, this value will exclude any recoveries."
70,LP_InterestandFees,"Pre charge-off cumulative interest and fees paid by the borrower. If the loan has charged off, this value will exclude any recoveries."
71,LP_ServiceFees,Cumulative service fees paid by the investors who have invested in the loan.
72,LP_CollectionFees,Cumulative collection fees paid by the investors who have invested in the loan.
73,LP_GrossPrincipalLoss,The gross charged off amount of the loan.
74,LP_NetPrincipalLoss,The principal that remains uncollected after any recoveries.
75,LP_NonPrincipalRecoverypayments,"The interest and fee component of any recovery payments. The current payment policy applies payments in the following order: Fees, interest, principal."
76,PercentFunded,Percent the listing was funded.
77,Recommendations,Number of recommendations the borrower had at the time the listing was created.
78,InvestmentFromFriendsCount,Number of friends that made an investment in the loan.
79,InvestmentFromFriendsAmount,Dollar amount of investments that were made by friends.
80,Investors,The number of investors that funded the loan.

<br><br>
**Programmatic Assessment**:
<br><br>
**Loan_Data**:

In [9]:
# getting a general information about the dataset
Loan_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 81 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   ListingKey                           113937 non-null  object
 1   ListingNumber                        113937 non-null  int64
 2   ListingCreationDate                  113937 non-null  object
 3   CreditGrade                          28953 non-null   object
 4   Term                                 113937 non-null  int64
 5   LoanStatus                           113937 non-null  object
 6   ClosedDate                           55089 non-null   object
 7   BorrowerAPR                          113912 non-null  float64
 8   BorrowerRate                         113937 non-null  float64
 9   LenderYield                          113937 non-null  float64
 10  EstimatedEffectiveYield              84853 non-null   float64
 11  EstimatedLoss                        84853 non-null   float64
 12  EstimatedReturn                      84853 non-null   float64
 13  ProsperRating (numeric)              84853 non-null   float64
 14  ProsperRating (Alpha)                84853 non-null   object
 15  ProsperScore                         84853 non-null   float64
 16  ListingCategory (numeric)            113937 non-null  int64
 17  BorrowerState                        108422 non-null  object
 18  Occupation                           110349 non-null  object
 19  EmploymentStatus                     111682 non-null  object
 20  EmploymentStatusDuration             106312 non-null  float64
 21  IsBorrowerHomeowner                  113937 non-null  bool
 22  CurrentlyInGroup                     113937 non-null  bool
 23  GroupKey                             13341 non-null   object
 24  DateCreditPulled                     113937 non-null  object
 25  CreditScoreRangeLower                113346 non-null  float64
 26  CreditScoreRangeUpper                113346 non-null  float64
 27  FirstRecordedCreditLine              113240 non-null  object
 28  CurrentCreditLines                   106333 non-null  float64
 29  OpenCreditLines                      106333 non-null  float64
 30  TotalCreditLinespast7years           113240 non-null  float64
 31  OpenRevolvingAccounts                113937 non-null  int64
 32  OpenRevolvingMonthlyPayment          113937 non-null  float64
 33  InquiriesLast6Months                 113240 non-null  float64
 34  TotalInquiries                       112778 non-null  float64
 35  CurrentDelinquencies                 113240 non-null  float64
 36  AmountDelinquent                     106315 non-null  float64
 37  DelinquenciesLast7Years              112947 non-null  float64
 38  PublicRecordsLast10Years             113240 non-null  float64
 39  PublicRecordsLast12Months            106333 non-null  float64
 40  RevolvingCreditBalance               106333 non-null  float64
 41  BankcardUtilization                  106333 non-null  float64
 42  AvailableBankcardCredit              106393 non-null  float64
 43  TotalTrades                          106393 non-null  float64
 44  TradesNeverDelinquent (percentage)   106393 non-null  float64
 45  TradesOpenedLast6Months              106393 non-null  float64
 46  DebtToIncomeRatio                    105383 non-null  float64
 47  IncomeRange                          113937 non-null  object
 48  IncomeVerifiable                     113937 non-null  bool
 49  StatedMonthlyIncome                  113937 non-null  float64
 50  LoanKey                              113937 non-null  object
 51  TotalProsperLoans                    22085 non-null   float64
 52  TotalProsperPaymentsBilled           22085 non-null   float64
 53  OnTimeProsperPayments                22085 non-null   float64
 54  ProsperPaymentsLessThanOneMonthLate  22085 non-null   float64
 55  ProsperPaymentsOneMonthPlusLate      22085 non-null   float64
 56  ProsperPrincipalBorrowed             22085 non-null   float64
 57  ProsperPrincipalOutstanding          22085 non-null   float64
 58  ScorexChangeAtTimeOfListing          18928 non-null   float64
 59  LoanCurrentDaysDelinquent            113937 non-null  int64
 60  LoanFirstDefaultedCycleNumber        16952 non-null   float64
 61  LoanMonthsSinceOrigination           113937 non-null  int64
 62  LoanNumber                           113937 non-null  int64
 63  LoanOriginalAmount                   113937 non-null  int64
 64  LoanOriginationDate                  113937 non-null  object
 65  LoanOriginationQuarter               113937 non-null  object
 66  MemberKey                            113937 non-null  object
 67  MonthlyLoanPayment                   113937 non-null  float64
 68  LP_CustomerPayments                  113937 non-null  float64
 69  LP_CustomerPrincipalPayments         113937 non-null  float64
 70  LP_InterestandFees                   113937 non-null  float64
 71  LP_ServiceFees                       113937 non-null  float64
 72  LP_CollectionFees                    113937 non-null  float64
 73  LP_GrossPrincipalLoss                113937 non-null  float64
 74  LP_NetPrincipalLoss                  113937 non-null  float64
 75  LP_NonPrincipalRecoverypayments      113937 non-null  float64
 76  PercentFunded                        113937 non-null  float64
 77  Recommendations                      113937 non-null  int64
 78  InvestmentFromFriendsCount           113937 non-null  int64
 79  InvestmentFromFriendsAmount          113937 non-null  float64
 80  Investors                            113937 non-null  int64
dtypes: bool(3), float64(50), int64(11), object(17)
memory usage: 68.1+ MB

In [10]:
# getting a sample of the dataset
Loan_Data.sample(15)

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperRating (Alpha),ProsperScore,ListingCategory (numeric),BorrowerState,Occupation,EmploymentStatus,EmploymentStatusDuration,IsBorrowerHomeowner,CurrentlyInGroup,GroupKey,DateCreditPulled,CreditScoreRangeLower,CreditScoreRangeUpper,FirstRecordedCreditLine,CurrentCreditLines,OpenCreditLines,TotalCreditLinespast7years,OpenRevolvingAccounts,OpenRevolvingMonthlyPayment,InquiriesLast6Months,TotalInquiries,CurrentDelinquencies,AmountDelinquent,DelinquenciesLast7Years,PublicRecordsLast10Years,PublicRecordsLast12Months,RevolvingCreditBalance,BankcardUtilization,AvailableBankcardCredit,TotalTrades,TradesNeverDelinquent (percentage),TradesOpenedLast6Months,DebtToIncomeRatio,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanKey,TotalProsperLoans,TotalProsperPaymentsBilled,OnTimeProsperPayments,ProsperPaymentsLessThanOneMonthLate,ProsperPaymentsOneMonthPlusLate,ProsperPrincipalBorrowed,ProsperPrincipalOutstanding,ScorexChangeAtTimeOfListing,LoanCurrentDaysDelinquent,LoanFirstDefaultedCycleNumber,LoanMonthsSinceOrigination,LoanNumber,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MemberKey,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_InterestandFees,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
31502,80F433765498632759F663A,72208,2006-12-08 12:47:26.793000000,HR,36,Defaulted,2007-05-14 00:00:00,0.29776,0.2900,0.2850,NaN,NaN,NaN,NaN,NaN,NaN,0,CA,Other,Not available,NaN,True,True,FE113364863511529673D04,2006-11-20 14:00:30.087000000,520.0,539.0,1996-02-22 00:00:00,NaN,NaN,19.0,2,16.0,12.0,50.0,3.0,NaN,20.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.15,Not displayed,True,5416.666667,4787337560380854012029E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222,6.0,87,5470,2600,2006-12-13 00:00:00,Q4 2006,B89F337484433303512ACD1,108.95,0.0000,0.00,0.0000,0.00,0.0,2600.00,2600.00,0.0,1.0000,0,0,0.0,27
111645,CAF83376539013187ECC44D,75171,2006-12-15 16:31:19.830000000,HR,36,Completed,2007-03-13 00:00:00,0.29972,0.2900,0.2850,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,Clerical,Not available,NaN,False,False,NaN,2006-12-03 01:12:01.077000000,480.0,499.0,2000-02-15 00:00:00,NaN,NaN,9.0,3,45.0,7.0,18.0,4.0,NaN,10.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.04,Not displayed,True,3916.666667,BC9F3377017024089754413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,87,5735,2000,2006-12-21 00:00:00,Q4 2006,1F7C337152910282443C900,83.81,2083.9000,2000.00,83.9000,-1.45,0.0,0.00,0.00,0.0,1.0000,0,0,0.0,30
43335,58053537249568436918D15,553174,2012-01-21 11:58:17.363000000,NaN,36,Completed,2012-11-19 00:00:00,0.24246,0.2049,0.1949,0.19040,0.0890,0.10140,4.0,C,7.0,1,CA,Medical Technician,Employed,76.0,True,False,NaN,2012-01-21 11:58:12,660.0,679.0,1998-06-29 00:00:00,8.0,8.0,29.0,6,255.0,4.0,8.0,0.0,5000.0,20.0,0.0,0.0,6324.0,0.24,6430.0,25.0,0.64,1.0,0.13,"$75,000-99,999",True,6600.000000,6A2036402985286390F752B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,26,59503,15000,2012-01-27 00:00:00,Q1 2012,52293537590561462B3E525,561.21,17253.6700,15000.00,2253.6700,-109.99,0.0,0.00,0.00,0.0,1.0000,0,0,0.0,85
25051,072333818403424801BEAFC,102696,2007-02-22 21:39:58.293000000,B,36,Completed,2010-03-14 00:00:00,0.16968,0.1625,0.1525,NaN,NaN,NaN,NaN,NaN,NaN,0,MD,Other,Self-employed,152.0,True,False,NaN,2007-02-15 20:00:09.870000000,680.0,699.0,1980-10-01 00:00:00,15.0,15.0,21.0,13,5478.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38639.0,0.88,2592.0,20.0,0.85,2.0,2.02,"$25,000-49,999",True,2464.250000,EA44338367195909357310D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,84,8485,19250,2007-03-14 00:00:00,Q1 2007,B1C133824840914594F24FC,652.62,24475.9300,19250.00,5225.9300,-321.60,0.0,0.00,0.00,0.0,1.0000,0,0,0.0,325
57075,9AD03517890923549F8C668,509104,2011-05-31 13:57:27.187000000,NaN,36,Completed,2011-06-29 00:00:00,0.35643,0.3199,0.3099,0.29170,0.2030,0.08870,1.0,HR,2.0,7,FL,Waiter/Waitress,Employed,72.0,False,False,NaN,2011-05-31 13:57:17,660.0,679.0,1997-11-07 00:00:00,9.0,8.0,22.0,6,92.0,6.0,8.0,1.0,9637.0,99.0,0.0,0.0,556.0,0.52,359.0,22.0,0.72,1.0,0.21,"$25,000-49,999",True,2750.000000,A5B13621402808832928788,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,33,50277,2933,2011-06-17 00:00:00,Q2 2011,57FA35176606297725B4562,127.73,2963.8600,2933.01,30.8500,-0.96,0.0,0.00,0.00,0.0,0.7332,0,0,0.0,53
73614,0B873588496660942D35CE6,880172,2013-08-26 11:04:34.237000000,NaN,60,Current,NaN,0.22283,0.1984,0.1884,0.17650,0.0674,0.10910,4.0,C,5.0,1,WI,Administrative Assistant,Full-time,99.0,False,False,NaN,2013-08-26 11:04:25,660.0,679.0,2002-09-20 00:00:00,8.0,7.0,14.0,4,153.0,1.0,2.0,1.0,441.0,0.0,0.0,0.0,4257.0,0.91,246.0,13.0,0.92,1.0,0.42,"$25,000-49,999",True,2854.833333,591D3692331598632A672C5,2.0,61.0,61.0,0.0,0.0,10700.0,2363.07,-48.0,0,NaN,7,100310,10000,2013-08-29 00:00:00,Q3 2013,9BC0347827502339811872A,264.05,1578.8644,614.34,964.5244,-48.88,0.0,0.00,0.00,0.0,1.0000,0,0,0.0,1
70557,08583578125194446C98148,774478,2013-05-09 14:32:12.887000000,NaN,60,Current,NaN,0.18136,0.1579,0.1479,0.14040,0.0499,0.09050,5.0,B,5.0,1,TX,Professional,Employed,40.0,True,False,NaN,2013-05-09 14:32:05,760.0,779.0,2000-03-29 00:00:00,7.0,6.0,25.0,8,371.0,0.0,0.0,1.0,2819.0,0.0,0.0,0.0,12766.0,0.59,8525.0,21.0,0.95,0.0,0.11,"$50,000-74,999",True,4666.666667,A1B13682868060051E58EB6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,9,91931,5000,2013-06-03 00:00:00,Q2 2013,0CD635790147508602011CE,121.03,1087.1070,525.34,561.7670,-35.72,0.0,0.00,0.00,0.0,1.0000,0,0,0.0,1
45772,7E0B3598435570307F1D9B8,1117821,2014-01-06 12:14:09.457000000,NaN,36,Current,NaN,0.14206,0.1139,0.1039,0.09989,0.0349,0.06499,6.0,A,5.0,1,TX,Sales - Retail,Self-employed,64.0,False,False,NaN,2014-01-06 12:14:11,700.0,719.0,1991-06-27 00:00:00,10.0,10.0,19.0,10,338.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,28674.0,0.46,33176.0,16.0,1.00,0.0,NaN,"$50,000-74,999",False,4166.666667,7D1E3702995333725F89EB2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,2,125854,15000,2014-01-08 00:00:00,Q1 2014,8CF03702420709786AE4018,493.86,987.7200,714.59,273.1300,-23.98,0.0,0.00,0.00,0.0,1.0000,0,0,0.0,1
57755,5D103574757225230DA2EF2,734594,2013-03-22 11:28:53.510000000,NaN,60,Current,NaN,0.26128,0.2359,0.2259,0.20850,0.0925,0.11600,3.0,D,3.0,7,NC,Teacher,Employed,128.0,False,False,NaN,2013-03-22 11:28:51,720.0,739.0,1997-07-03 00:00:00,6.0,6.0,26.0,6,479.0,0.0,1.0,0.0,0.0,7.0,0.0,0.0,9747.0,0.96,50.0,21.0,0.76,0.0,0.31,"$25,000-49,999",True,2500.000000,BED13677960392103B36483,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,12,87248,2000,2013-03-27 00:00:00,Q1 2013,AF443574419534983E07C8B,57.06,627.6600,212.32,415.3400,-17.61,0.0,0.00,0.00,0.0,1.0000,0,0,0.0,29
11621,15523523880789703BCCCE8,521762,2011-08-15 08:39:51.487000000,NaN,36,Chargedoff,2012-07-31 00:00:00,0.35643,0.3199,0.3099,0.29570,0.1470,0.14870,2.0,E,4.0,3,WA,Investor,Self-employed,14.0,False,False,NaN,2011-08-15 08:39:47,740.0,759.0,2004-04-08 00:00:00,2.0,2.0,6.0,2,41.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1300.0,6.0,1.00,1.0,NaN,"$25,000-49,999",False,3000.000000,924C3627526143753637074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,709,11.0,31,52900,2000,2011-08-31 00:00:00,Q3 2011,69B335238744242637D5B33,87.10,522.6000,200.99,321.6100,-6.36,0.0,1799.01,1799.01,0.0,1.0000,0,0,0.0,40
43104,3C6D358581951896674EBFA,852526,2013-07-26 13:37:44.773000000,NaN,36,Completed,2013-08-01 00:00:00,0.08325,0.0699,0.0599,0.05900,0.0124,0.04660,7.0,AA,10.0,13,NY,Analyst,Employed,73.0,False,True,52EA3425051368132B80C96,2013-07-26 13:37:33,800.0,819.0,1998-07-08 00:00:00,8.0,7.0,29.0,5,98.0,0.0,1.0,1.0,382.0,0.0,0.0,0.0,6990.0,0.05,117210.0,28.0,0.96,0.0,0.07,"$100,000+",True,11299.583333,6E493689460183567D5C638,4.0,52.0,52.0,0.0,0.0,10174.0,492.49,71.0,0,NaN,8,96921,2000,2013-07-30 00:00:00,Q3 2013,F8B73412947193422E9D687,61.75,2000.7600,1999.99,0.7700,-0.11,0.0,0.00,0.00,0.0,1.0000,1,0,0.0,41
34006,38D23544800746336E6EB67,581782,2012-04-23 20:49:47.817000000,NaN,36,Current,NaN,0.35797,0.3177,0.3077,0.28960,0.1650,0.12460,1.0,HR,4.0,9,FL,Other,Employed,19.0,False,False,NaN,2012-04-23 20:49:43,660.0,679.0,1997-04-07 00:00:00,1.0,1.0,3.0,1,0.0,1.0,1.0,2.0,145.0,0.0,0.0,0.0,0.0,0.00,4000.0,2.0,0.33,0.0,0.07,"$25,000-49,999",True,2500.000000,2ADD3648543407522F6B33B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,23,64696,4000,2012-04-27 00:00:00,Q2 2012,9D3D35459169117404FDFD0,173.71,3821.6200,1984.67,1836.9500,-57.83,0.0,0.00,0.00,0.0,1.0000,0,0,0.0,34
30808,BAA83393403466748BA9EEF,155539,2007-06-20 17:51:46.877000000,E,36,Chargedoff,2008-11-06 00:00:00,0.26213,0.2469,0.2269,NaN,NaN,NaN,NaN,NaN,NaN,0,CA,Construction,Full-time,4.0,False,True,85943386927308216031C0F,2007-06-11 19:36:01.870000000,580.0,599.0,2001-05-18 00:00:00,7.0,4.0,12.0,3,98.0,3.0,15.0,0.0,0.0,1.0,0.0,0.0,0.0,0.00,0.0,9.0,0.66,1.0,0.23,"$25,000-49,999",True,4909.666667,F6FC33941829460673E3771,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2074,16.0,80,16665,12000,2007-07-05 00:00:00,Q3 2007,FFD833912915895065F5C20,475.15,5112.8700,2429.28,2683.5900,-78.60,-85.0,9570.73,9570.72,0.0,1.0000,0,0,0.0,187
60081,C33C3597752178869698BA9,1070164,2013-12-31 11:33:15.200000000,NaN,36,Current,NaN,0.15223,0.1239,0.1139,0.10900,0.0399,0.06910,6.0,A,9.0,1,NJ,Other,Employed,79.0,True,False,NaN,2013-12-31 11:33:18,720.0,739.0,1999-09-22 00:00:00,14.0,14.0,42.0,15,750.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0,23063.0,0.28,58537.0,41.0,1.00,1.0,0.20,"$75,000-99,999",True,7916.666667,88CE370325944006101B2FA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,2,124957,25000,2014-01-03 00:00:00,Q1 2014,EC0B37029211695182BFFF8,835.02,1661.5537,1279.89,381.6637,-31.49,0.0,0.00,0.00,0.0,1.0000,0,0,0.0,1
63030,EBE7336583190625554E93A,12237,2006-05-08 23:29:27.750000000,C,36,Completed,2009-05-16 00:00:00,0.18726,0.1800,0.1600,NaN,NaN,NaN,NaN,NaN,NaN,0,TX,NaN,NaN,NaN,False,False,A8113366311579615424760,2006-05-08 23:19:04.240000000,640.0,659.0,1986-11-01 00:00:00,NaN,NaN,18.0,0,0.0,1.0,NaN,0.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.14,Not displayed,True,7916.666667,1EE43365178874956986792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,94,926,4000,2006-05-16 00:00:00,Q2 2006,74343366457975011287ABF,140.55,5109.1800,4000.00,1109.1800,-33.61,0.0,0.00,0.00,0.0,1.0000,0,0,0.0,40

In [29]:
# checking for data duplication based on ListingNumber 
Loan_Data['ListingNumber'].duplicated().any()

True

In [12]:
# dataset's shape 
Loan_Data.shape

(113937, 81)

In [13]:
Loan_Data['EmploymentStatus'].value_counts()

Employed         67322
Full-time        26355
Self-employed     6134
Not available     5347
Other             3806
Part-time         1088
Not employed       835
Retired            795
Name: EmploymentStatus, dtype: int64

In [26]:
Loan_Data['ProsperRating (numeric)'].isnull().sum()

29084

In [14]:
# getting descriptive statistics of the numeric variables
Loan_Data.describe()

,ListingNumber,Term,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperScore,ListingCategory (numeric),EmploymentStatusDuration,CreditScoreRangeLower,CreditScoreRangeUpper,CurrentCreditLines,OpenCreditLines,TotalCreditLinespast7years,OpenRevolvingAccounts,OpenRevolvingMonthlyPayment,InquiriesLast6Months,TotalInquiries,CurrentDelinquencies,AmountDelinquent,DelinquenciesLast7Years,PublicRecordsLast10Years,PublicRecordsLast12Months,RevolvingCreditBalance,BankcardUtilization,AvailableBankcardCredit,TotalTrades,TradesNeverDelinquent (percentage),TradesOpenedLast6Months,DebtToIncomeRatio,StatedMonthlyIncome,TotalProsperLoans,TotalProsperPaymentsBilled,OnTimeProsperPayments,ProsperPaymentsLessThanOneMonthLate,ProsperPaymentsOneMonthPlusLate,ProsperPrincipalBorrowed,ProsperPrincipalOutstanding,ScorexChangeAtTimeOfListing,LoanCurrentDaysDelinquent,LoanFirstDefaultedCycleNumber,LoanMonthsSinceOrigination,LoanNumber,LoanOriginalAmount,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_InterestandFees,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
count,1.139370e+05,113937.000000,113912.000000,113937.000000,113937.000000,84853.000000,84853.000000,84853.000000,84853.000000,84853.000000,113937.000000,106312.000000,113346.000000,113346.000000,106333.000000,106333.000000,113240.000000,113937.00000,113937.000000,113240.000000,112778.000000,113240.000000,106315.000000,112947.000000,113240.000000,106333.000000,1.063330e+05,106333.000000,106393.000000,106393.000000,106393.000000,106393.000000,105383.000000,1.139370e+05,22085.000000,22085.000000,22085.000000,22085.000000,22085.000000,22085.000000,22085.000000,18928.000000,113937.000000,16952.000000,113937.000000,113937.000000,113937.00000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000
mean,6.278857e+05,40.830248,0.218828,0.192764,0.182701,0.168661,0.080306,0.096068,4.072243,5.950067,2.774209,96.071582,685.567731,704.567731,10.317192,9.260164,26.754539,6.96979,398.292161,1.435085,5.584405,0.592052,984.507059,4.154984,0.312646,0.015094,1.759871e+04,0.561309,11210.225447,23.230034,0.885897,0.802327,0.275947,5.608026e+03,1.421100,22.934345,22.271949,0.613629,0.048540,8472.311961,2930.313906,-3.223214,152.816539,16.268464,31.896882,69444.474271,8337.01385,272.475783,4183.079489,3105.536588,1077.542901,-54.725641,-14.242698,700.446342,681.420499,25.142686,0.998584,0.048027,0.023460,16.550751,80.475228
std,3.280762e+05,10.436212,0.080364,0.074818,0.074516,0.068467,0.046764,0.030403,1.673227,2.376501,3.996797,94.480605,66.458275,66.458275,5.457866,5.022644,13.637871,4.63097,447.159711,2.437507,6.429946,1.978707,7158.270157,10.160216,0.727868,0.154092,3.293640e+04,0.317918,19818.361309,11.871311,0.148179,1.097637,0.551759,7.478497e+03,0.764042,19.249584,18.830425,2.446827,0.556285,7395.507650,3806.635075,50.063567,466.320254,9.005898,29.974184,38930.479610,6245.80058,192.697812,4790.907234,4069.527670,1183.414168,60.675425,109.232758,2388.513831,2357.167068,275.657937,0.017919,0.332353,0.232412,294.545422,103.239020
min,4.000000e+00,12.000000,0.006530,0.000000,-0.010000,-0.182700,0.004900,-0.182700,1.000000,1.000000,0.000000,0.000000,0.000000,19.000000,0.000000,0.000000,2.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-209.000000,0.000000,0.000000,0.000000,1.000000,1000.00000,0.000000,-2.349900,0.000000,-2.349900,-664.870000,-9274.750000,-94.200000,-954.550000,0.000000,0.700000,0.000000,0.000000,0.000000,1.000000
25%,4.009190e+05,36.000000,0.156290,0.134000,0.124200,0.115670,0.042400,0.074080,3.000000,4.000000,1.000000,26.000000,660.000000,679.000000,7.000000,6.000000,17.000000,4.00000,114.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.121000e+03,0.310000,880.000000,15.000000,0.820000,0.000000,0.140000,3.200333e+03,1.000000,9.000000,9.000000,0.000000,0.000000,3500.000000,0.000000,-35.000000,0.000000,9.000000,6.000000,37332.000000,4000.00000,131.620000,1005.760000,500.890000,274.870000,-73.180000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2.000000
50%,6.005540e+05,36.000000,0.209760,0.184000,0.173000,0.161500,0.072400,0.091700,4.000000,6.000000,1.000000,67.000000,680.000000,699.000000,10.000000,9.000000,25.000000,6.00000,271.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.549000e+03,0.600000,4100.000000,22.000000,0.940000,0.000000,0.220000,4.666667e+03,1.000000,16.000000,15.000000,0.000000,0.000000,6000.000000,1626.550000,-3.000000,0.000000,14.000000,21.000000,68599.000000,6500.00000,217.740000,2583.830000,1587.500000,700.840100,-34.440000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,44.000000
75%,8.926340e+05,36.000000,0.283810,0.250000,0.240000,0.224300,0.112000,0.116600,5.000000,8.000000,3.000000,137.000000,720.000000,739.000000,13.000000,12.000000,35.000000,9.00000,525.000000,2.000000,7.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.952100e+04,0.840000,13180.000000,30.000000,1.000000,1.000000,0.320000,6.825000e+03,2.000000,33.000000,32.000000,0.000000,0.000000,11000.000000,4126.720000,25.000000,0.000000,22.000000,65.000000,101901.000000,12000.00000,371.580000,5548.400000,4000.000000,1458.540000,-13.920000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,115.000000
max,1.255725e+06,60.000000,0.512290,0.497500,0.492500,0.319900,0.366000,0.283700,7.000000,11.000000,20.000000,755.000000,880.000000,899.000000,59.000000,54.000000,136.000000,51.00000,14985.000000,105.000000,379.000000,83.000000,463881.000000,99.000000,38.000000,20.000000,1.435667e+06,5.950000,646285.000000,126.000000,1.000000,20.000000,10.010000,1.750003e+06,8.000000,141.000000,141.000000,42.000000,21.000000,72499.000000,23450.950000,286.000000,2704.000000,44.000000,100.000000,136486.000000,35000.00000,2251.510000,40702.390000,35000.000000,15617.030000,32.060000,0.000000,25000.000000,25000.000000,21117.900000,1.012500,39.000000,33.000000,25000.000000,1189.000000

In [17]:
# Check for null values 
Loan_Data.isnull().sum()

ListingKey                                  0
ListingNumber                               0
ListingCreationDate                         0
CreditGrade                             84984
Term                                        0
LoanStatus                                  0
ClosedDate                              58848
BorrowerAPR                                25
BorrowerRate                                0
LenderYield                                 0
EstimatedEffectiveYield                 29084
EstimatedLoss                           29084
EstimatedReturn                         29084
ProsperRating (numeric)                 29084
ProsperRating (Alpha)                   29084
ProsperScore                            29084
ListingCategory (numeric)                   0
BorrowerState                            5515
Occupation                               3588
EmploymentStatus                         2255
EmploymentStatusDuration                 7625
IsBorrowerHomeowner                         0
CurrentlyInGroup                            0
GroupKey                               100596
DateCreditPulled                            0
CreditScoreRangeLower                     591
CreditScoreRangeUpper                     591
FirstRecordedCreditLine                   697
CurrentCreditLines                       7604
OpenCreditLines                          7604
TotalCreditLinespast7years                697
OpenRevolvingAccounts                       0
OpenRevolvingMonthlyPayment                 0
InquiriesLast6Months                      697
TotalInquiries                           1159
CurrentDelinquencies                      697
AmountDelinquent                         7622
DelinquenciesLast7Years                   990
PublicRecordsLast10Years                  697
PublicRecordsLast12Months                7604
RevolvingCreditBalance                   7604
BankcardUtilization                      7604
AvailableBankcardCredit                  7544
TotalTrades                              7544
TradesNeverDelinquent (percentage)       7544
TradesOpenedLast6Months                  7544
DebtToIncomeRatio                        8554
IncomeRange                                 0
IncomeVerifiable                            0
StatedMonthlyIncome                         0
LoanKey                                     0
TotalProsperLoans                       91852
TotalProsperPaymentsBilled              91852
OnTimeProsperPayments                   91852
ProsperPaymentsLessThanOneMonthLate     91852
ProsperPaymentsOneMonthPlusLate         91852
ProsperPrincipalBorrowed                91852
ProsperPrincipalOutstanding             91852
ScorexChangeAtTimeOfListing             95009
LoanCurrentDaysDelinquent                   0
LoanFirstDefaultedCycleNumber           96985
LoanMonthsSinceOrigination                  0
LoanNumber                                  0
LoanOriginalAmount                          0
LoanOriginationDate                         0
LoanOriginationQuarter                      0
MemberKey                                   0
MonthlyLoanPayment                          0
LP_CustomerPayments                         0
LP_CustomerPrincipalPayments                0
LP_InterestandFees                          0
LP_ServiceFees                              0
LP_CollectionFees                           0
LP_GrossPrincipalLoss                       0
LP_NetPrincipalLoss                         0
LP_NonPrincipalRecoverypayments             0
PercentFunded                               0
Recommendations                             0
InvestmentFromFriendsCount                  0
InvestmentFromFriendsAmount                 0
Investors                                   0
dtype: int64

### Data Assessment Summary:
1. The dataset contans a lot of null values
2. Too many variables for the Purpose of the investigation
3. There are ListingNumber duplication 
4. Erroneous datatypes for `TotalTrades, TotalInquiries, and ListingCategory (numeric)`
5. There are null values in ProsperRating (numeric) column 
6. The time, day, month and year are combined in `ListingCreationDate` column.

<br><br><br>
### Data Cleaning
1. Fill in the null values of occupation and DebtToIncomeRatio
2. Pick out features of intrest
3. Drop the rows with ListingNumber duplication
4. Change `TotalTrades and TotalInquiries` datatypes to Integer, and `ListingCategory (numeric)` to Category
5. Drop rows with no ProsperRating data
6. Separate the time, day, month and year into four columns from `ListingCreationDate` column and give names to the months

In [30]:
# Pick out features of intrest
#Code:
features_intrest= ['ListingNumber','ListingCreationDate','LoanOriginalAmount','LoanStatus','ListingCategory (numeric)','BorrowerState','BorrowerAPR','BorrowerRate','StatedMonthlyIncome', 'ProsperRating (Alpha)', 
        'Occupation','Term','EmploymentStatus','TotalInquiries','DebtToIncomeRatio','MonthlyLoanPayment','TotalTrades','Investors']
Loan_Data_subset= Loan_Data[features_intrest]

In [31]:
#Test: data information
Loan_Data_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 18 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ListingNumber              113937 non-null  int64
 1   ListingCreationDate        113937 non-null  object
 2   LoanOriginalAmount         113937 non-null  int64
 3   LoanStatus                 113937 non-null  object
 4   ListingCategory (numeric)  113937 non-null  int64
 5   BorrowerState              108422 non-null  object
 6   BorrowerAPR                113912 non-null  float64
 7   BorrowerRate               113937 non-null  float64
 8   StatedMonthlyIncome        113937 non-null  float64
 9   ProsperRating (Alpha)      84853 non-null   object
 10  Occupation                 110349 non-null  object
 11  Term                       113937 non-null  int64
 12  EmploymentStatus           111682 non-null  object
 13  TotalInquiries             112778 non-null  float64
 14  DebtToIncomeRatio          105383 non-null  float64
 15  MonthlyLoanPayment         113937 non-null  float64
 16  TotalTrades                106393 non-null  float64
 17  Investors                  113937 non-null  int64
dtypes: float64(7), int64(5), object(6)
memory usage: 15.6+ MB

In [32]:
#Test: sample of the data
Loan_Data_subset.sample(15)

,ListingNumber,ListingCreationDate,LoanOriginalAmount,LoanStatus,ListingCategory (numeric),BorrowerState,BorrowerAPR,BorrowerRate,StatedMonthlyIncome,ProsperRating (Alpha),Occupation,Term,EmploymentStatus,TotalInquiries,DebtToIncomeRatio,MonthlyLoanPayment,TotalTrades,Investors
108788,749084,2013-04-10 18:22:29.900000000,15000,Current,1,AZ,0.22283,0.1984,4333.333333,C,Engineer - Mechanical,60,Employed,5.0,0.43000,396.07,28.0,1
14380,1173609,2014-01-30 15:48:50.273000000,12000,Current,1,VA,0.14206,0.1139,4500.000000,A,Other,36,Employed,2.0,0.25000,395.08,10.0,121
36793,1009803,2013-10-27 11:35:07.377000000,15000,Current,1,TX,0.12274,0.0949,8666.666667,A,Professional,36,Employed,5.0,0.19000,480.42,38.0,183
100429,69396,2006-12-02 12:15:48.637000000,4500,Completed,0,CO,0.08584,0.0790,5833.333333,NaN,Analyst,36,Not available,3.0,0.12000,140.81,NaN,129
105772,563794,2012-02-28 18:48:24.023000000,4500,Current,18,TN,0.28370,0.2452,2166.666667,D,Other,36,Employed,0.0,0.11000,177.78,6.0,42
9952,1230225,2014-02-23 12:51:10.273000000,3200,Current,1,OH,0.18518,0.1485,1000.000000,B,Sales - Retail,36,Employed,0.0,0.52000,110.69,17.0,1
79531,699920,2013-01-16 09:59:47.200000000,4000,Current,7,FL,0.31790,0.2786,2083.333333,E,Other,36,Self-employed,2.0,NaN,165.15,12.0,65
85618,544378,2011-12-12 17:30:14.760000000,4000,Current,1,FL,0.35285,0.3127,3000.000000,HR,Other,36,Self-employed,2.0,NaN,172.60,29.0,4
48527,649688,2012-10-04 16:45:17.930000000,9900,Current,1,FL,0.27462,0.2489,3583.333333,D,Administrative Assistant,60,Employed,3.0,0.24000,289.94,15.0,113
40852,429907,2009-10-23 06:35:28.070000000,3000,Completed,2,VA,0.28777,0.2645,2353.666667,D,Medical Technician,36,Full-time,1.0,0.38000,121.59,31.0,126
87290,6475,2006-04-18 13:51:13.953000000,5000,Completed,0,NaN,0.10190,0.0950,11250.000000,NaN,NaN,36,NaN,NaN,0.09593,158.58,NaN,59
55314,933277,2013-10-01 13:36:55.420000000,6000,Current,1,CA,0.15833,0.1299,5166.666667,A,Food Service,36,Employed,9.0,0.23000,202.13,25.0,1
24052,617252,2012-07-26 18:39:59.747000000,4000,Chargedoff,2,FL,0.33665,0.2969,8166.666667,E,Medical Technician,36,Employed,5.0,0.11000,169.13,33.0,33
39026,689131,2012-12-19 18:10:21.563000000,3000,Current,15,TX,0.27285,0.2346,3600.000000,D,Other,36,Employed,0.0,0.22000,116.84,28.0,54
106223,1139359,2014-01-31 06:55:18.307000000,2000,Current,1,FL,0.34588,0.3059,5833.333333,HR,Construction,36,Employed,4.0,0.42000,85.55,26.0,1

In [36]:
# Drop the rows with ListingNumber duplication  
#Code:
Loan_Data_subset.drop_duplicates(inplace=True)

<ipython-input-36-a90e2ed42f0a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Loan_Data_subset.drop_duplicates(inplace=True)

In [39]:
#Test: data information
Loan_Data_subset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113066 entries, 0 to 113936
Data columns (total 18 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ListingNumber              113066 non-null  int64
 1   ListingCreationDate        113066 non-null  object
 2   LoanOriginalAmount         113066 non-null  int64
 3   LoanStatus                 113066 non-null  object
 4   ListingCategory (numeric)  113066 non-null  int64
 5   BorrowerState              107551 non-null  object
 6   BorrowerAPR                113041 non-null  float64
 7   BorrowerRate               113066 non-null  float64
 8   StatedMonthlyIncome        113066 non-null  float64
 9   ProsperRating (Alpha)      83982 non-null   object
 10  Occupation                 109537 non-null  object
 11  Term                       113066 non-null  int64
 12  EmploymentStatus           110811 non-null  object
 13  TotalInquiries             111907 non-null  float64
 14  DebtToIncomeRatio          104594 non-null  float64
 15  MonthlyLoanPayment         113066 non-null  float64
 16  TotalTrades                105522 non-null  float64
 17  Investors                  113066 non-null  int64
dtypes: float64(7), int64(5), object(6)
memory usage: 16.4+ MB

In [38]:
#Test: Check for duplication
Loan_Data_subset.duplicated().any()

False

In [41]:
#Drop rows with no ProsperRating data
#Code:
Loan_Data_subset= Loan_Data_subset[Loan_Data_subset['ProsperRating (Alpha)'].notnull()]

In [42]:
#Test: data information
Loan_Data_subset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83982 entries, 1 to 113936
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ListingNumber              83982 non-null  int64
 1   ListingCreationDate        83982 non-null  object
 2   LoanOriginalAmount         83982 non-null  int64
 3   LoanStatus                 83982 non-null  object
 4   ListingCategory (numeric)  83982 non-null  int64
 5   BorrowerState              83982 non-null  object
 6   BorrowerAPR                83982 non-null  float64
 7   BorrowerRate               83982 non-null  float64
 8   StatedMonthlyIncome        83982 non-null  float64
 9   ProsperRating (Alpha)      83982 non-null  object
 10  Occupation                 82708 non-null  object
 11  Term                       83982 non-null  int64
 12  EmploymentStatus           83982 non-null  object
 13  TotalInquiries             83982 non-null  float64
 14  DebtToIncomeRatio          76768 non-null  float64
 15  MonthlyLoanPayment         83982 non-null  float64
 16  TotalTrades                83982 non-null  float64
 17  Investors                  83982 non-null  int64
dtypes: float64(7), int64(5), object(6)
memory usage: 12.2+ MB

In [44]:
#Test: Check for null values
Loan_Data_subset['ProsperRating (Alpha)'].isnull().any()

False

In [45]:
#Fill in the null values of occupation and DebtToIncomeRatio
#Code 1:
Loan_Data_subset['Occupation'] = Loan_Data_subset['Occupation'].fillna('Unknown')

<ipython-input-45-00f5a869774e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Loan_Data_subset['Occupation'] = Loan_Data_subset['Occupation'].fillna('Unknown')

In [46]:
#Code 2:
Loan_Data_subset['DebtToIncomeRatio'] = Loan_Data_subset['DebtToIncomeRatio'].fillna(Loan_Data_subset['DebtToIncomeRatio'].mean())

<ipython-input-46-4801af2e8727>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Loan_Data_subset['DebtToIncomeRatio'] = Loan_Data_subset['DebtToIncomeRatio'].fillna(Loan_Data_subset['DebtToIncomeRatio'].mean())

In [49]:
# Test: data information
Loan_Data_subset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83982 entries, 1 to 113936
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ListingNumber              83982 non-null  int64
 1   ListingCreationDate        83982 non-null  object
 2   LoanOriginalAmount         83982 non-null  int64
 3   LoanStatus                 83982 non-null  object
 4   ListingCategory (numeric)  83982 non-null  int64
 5   BorrowerState              83982 non-null  object
 6   BorrowerAPR                83982 non-null  float64
 7   BorrowerRate               83982 non-null  float64
 8   StatedMonthlyIncome        83982 non-null  float64
 9   ProsperRating (Alpha)      83982 non-null  object
 10  Occupation                 83982 non-null  object
 11  Term                       83982 non-null  int64
 12  EmploymentStatus           83982 non-null  object
 13  TotalInquiries             83982 non-null  float64
 14  DebtToIncomeRatio          83982 non-null  float64
 15  MonthlyLoanPayment         83982 non-null  float64
 16  TotalTrades                83982 non-null  float64
 17  Investors                  83982 non-null  int64
dtypes: float64(7), int64(5), object(6)
memory usage: 12.2+ MB

In [48]:
# Test 1: Check for null values in Occupation
Loan_Data_subset['Occupation'].isnull().any()

False

In [51]:
# Test 2: Check for null values in DebtToIncomeRatio
Loan_Data_subset['DebtToIncomeRatio'].isnull().any()

False

In [52]:
#Change TotalTrades and TotalInquiries datatypes to Integer, and ListingCategory (numeric) to Category
#Code 1:
Loan_Data_subset['TotalInquiries'] = Loan_Data_subset['TotalInquiries'].astype(int)
Loan_Data_subset['TotalTrades'] = Loan_Data_subset['TotalTrades'].astype(int)

<ipython-input-52-43663ad12521>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Loan_Data_subset['TotalInquiries'] = Loan_Data_subset['TotalInquiries'].astype(int)
<ipython-input-52-43663ad12521>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Loan_Data_subset['TotalTrades'] = Loan_Data_subset['TotalTrades'].astype(int)

In [57]:
# Code 2:
Loan_Data_subset['ListingCategory (numeric)'] = Loan_Data_subset['ListingCategory (numeric)'].astype("category")

<ipython-input-57-27d78cfe6791>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Loan_Data_subset['ListingCategory (numeric)'] = Loan_Data_subset['ListingCategory (numeric)'].astype("category")

In [58]:
# Test: data information
Loan_Data_subset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83982 entries, 1 to 113936
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ListingNumber              83982 non-null  int64
 1   ListingCreationDate        83982 non-null  object
 2   LoanOriginalAmount         83982 non-null  int64
 3   LoanStatus                 83982 non-null  object
 4   ListingCategory (numeric)  83982 non-null  category
 5   BorrowerState              83982 non-null  object
 6   BorrowerAPR                83982 non-null  float64
 7   BorrowerRate               83982 non-null  float64
 8   StatedMonthlyIncome        83982 non-null  float64
 9   ProsperRating (Alpha)      83982 non-null  object
 10  Occupation                 83982 non-null  object
 11  Term                       83982 non-null  int64
 12  EmploymentStatus           83982 non-null  object
 13  TotalInquiries             83982 non-null  int64
 14  DebtToIncomeRatio          83982 non-null  float64
 15  MonthlyLoanPayment         83982 non-null  float64
 16  TotalTrades                83982 non-null  int64
 17  Investors                  83982 non-null  int64
dtypes: category(1), float64(5), int64(6), object(6)
memory usage: 11.6+ MB

In [61]:
# Test 1 and 2: Check for TotalTrades, TotalInquiries and ListingCategory (numeric) datatypes
print(Loan_Data_subset['TotalInquiries'].dtypes)
print(Loan_Data_subset['TotalTrades'].dtypes)
print(Loan_Data_subset['ListingCategory (numeric)'].dtypes)

int64
int64
category

In [62]:
# Separate the time, day, month and year into four columns from `ListingCreationDate` column and give names to the months
#Code 1: Splitting into year
Loan_Data_subset['Year']=Loan_Data_subset['ListingCreationDate'].apply(lambda x: x.split("-")[0]).astype(str)

<ipython-input-62-db65952e4099>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Loan_Data_subset['Year']=Loan_Data_subset['ListingCreationDate'].apply(lambda x: x.split("-")[0]).astype(str)

In [69]:
#Test 1: sample of the Year column
Loan_Data_subset['Year'].sample(10)

78272    2012
75336    2012
56876    2012
82213    2012
50922    2014
62749    2011
19699    2013
66641    2012
7498     2010
54832    2012
Name: Year, dtype: object

In [66]:
#Code 2.1: Splitting into month
Loan_Data_subset['Month'] = Loan_Data_subset['ListingCreationDate'].apply(lambda x: x.split("-")[1]).astype(str)

<ipython-input-66-60b61308852c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Loan_Data_subset['Month'] = Loan_Data_subset['ListingCreationDate'].apply(lambda x: x.split("-")[1]).astype(str)

In [68]:
#Test 2.1: sample of the Month column
Loan_Data_subset['Month'].sample(10)

44484    05
28593    02
93822    11
67008    03
84951    03
52952    10
28559    04
38001    09
90995    09
85537    09
Name: Month, dtype: object

In [72]:
#Code 2.2: give names to the months instead of the numbers
Loan_Data_subset['Month'].replace(['01','02','03','04','05','06','07','08','09','10','11','12'],['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sept','Oct','Nov','Dec'],inplace = True)

/Users/yara/opt/anaconda3/envs/last_project/lib/python3.8/site-packages/pandas/core/series.py:4563: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [73]:
#Test 2.2: sample of the Month column
Loan_Data_subset['Month'].sample(10)

70538      May
13657      Dec
6399       Nov
51506      Oct
90889      Dec
95290      May
58957      Aug
23845     Sept
105301     Jan
88365      Aug
Name: Month, dtype: object

In [75]:
#Code:
Loan_Data_subset['ListingCreationDate'] = Loan_Data_subset['ListingCreationDate'].apply(lambda x: x.split("-")[2]).astype(str)

<ipython-input-75-04eb06ef3b2f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Loan_Data_subset['ListingCreationDate'] = Loan_Data_subset['ListingCreationDate'].apply(lambda x: x.split("-")[2]).astype(str)

In [76]:
#Code 3:
Loan_Data_subset['Day'] = Loan_Data_subset['ListingCreationDate'].apply(lambda x: x.split(" ")[0]).astype(str)

<ipython-input-76-bbfc5bc165f1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Loan_Data_subset['Day'] = Loan_Data_subset['ListingCreationDate'].apply(lambda x: x.split(" ")[0]).astype(str)

In [77]:
#Test 3: sample of Day column
Loan_Data_subset['Day'].sample(5)

818       24
102838    02
105738    07
98056     18
70413     04
Name: Day, dtype: object

In [78]:
#Code 4:
Loan_Data_subset['Time'] = Loan_Data_subset['ListingCreationDate'].apply(lambda x: x.split(" ")[1]).astype(str)

<ipython-input-78-af1599ea0ab4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Loan_Data_subset['Time'] = Loan_Data_subset['ListingCreationDate'].apply(lambda x: x.split(" ")[1]).astype(str)

In [79]:
#Test 4: sample of Time column
Loan_Data_subset['Time'].sample(5)

2626      10:58:34.777000000
93849     10:16:44.640000000
91533     21:12:44.480000000
104832    08:02:17.457000000
85446     06:50:38.203000000
Name: Time, dtype: object

In [80]:
# Code: Dropping the ListingCreationDate column
Loan_Data_subset.drop(columns = ['ListingCreationDate'],inplace = True)

/Users/yara/opt/anaconda3/envs/last_project/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [81]:
#Test: data information
Loan_Data_subset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83982 entries, 1 to 113936
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ListingNumber              83982 non-null  int64
 1   LoanOriginalAmount         83982 non-null  int64
 2   LoanStatus                 83982 non-null  object
 3   ListingCategory (numeric)  83982 non-null  category
 4   BorrowerState              83982 non-null  object
 5   BorrowerAPR                83982 non-null  float64
 6   BorrowerRate               83982 non-null  float64
 7   StatedMonthlyIncome        83982 non-null  float64
 8   ProsperRating (Alpha)      83982 non-null  object
 9   Occupation                 83982 non-null  object
 10  Term                       83982 non-null  int64
 11  EmploymentStatus           83982 non-null  object
 12  TotalInquiries             83982 non-null  int64
 13  DebtToIncomeRatio          83982 non-null  float64
 14  MonthlyLoanPayment         83982 non-null  float64
 15  TotalTrades                83982 non-null  int64
 16  Investors                  83982 non-null  int64
 17  Year                       83982 non-null  object
 18  Month                      83982 non-null  object
 19  Day                        83982 non-null  object
 20  Time                       83982 non-null  object
dtypes: category(1), float64(5), int64(6), object(9)
memory usage: 13.5+ MB

<br><br><br>
## Exploratory Data Analysis (EDA)

In [82]:
#Descriptive Statistics
Loan_Data_subset.describe()

,ListingNumber,LoanOriginalAmount,BorrowerAPR,BorrowerRate,StatedMonthlyIncome,Term,TotalInquiries,DebtToIncomeRatio,MonthlyLoanPayment,TotalTrades,Investors
count,8.398200e+04,83982.000000,83982.000000,83982.00000,8.398200e+04,83982.000000,83982.000000,83982.000000,83982.00000,83982.000000,83982.000000
mean,7.712395e+05,9061.224381,0.226945,0.19630,5.930614e+03,42.462813,4.285514,0.258692,291.40139,23.925115,68.677788
std,2.359100e+05,6279.649648,0.080047,0.07475,8.268432e+03,11.639032,3.828780,0.305687,186.47539,11.610432,95.318077
min,4.162750e+05,1000.000000,0.045830,0.04000,0.000000e+00,12.000000,0.000000,0.000000,0.00000,1.000000,1.000000
25%,5.570608e+05,4000.000000,0.163610,0.13590,3.426938e+03,36.000000,2.000000,0.160000,157.11250,15.000000,1.000000
50%,7.341785e+05,7500.000000,0.219450,0.18750,5.000000e+03,36.000000,3.000000,0.240000,251.28000,23.000000,32.000000
75%,9.756778e+05,13500.000000,0.292540,0.25740,7.083333e+03,60.000000,6.000000,0.310000,387.62000,31.000000,98.000000
max,1.255725e+06,35000.000000,0.423950,0.36000,1.750003e+06,60.000000,78.000000,10.010000,2251.51000,122.000000,1189.000000

In [83]:
# a general look at the cleaned dataset
Loan_Data_subset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83982 entries, 1 to 113936
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ListingNumber              83982 non-null  int64
 1   LoanOriginalAmount         83982 non-null  int64
 2   LoanStatus                 83982 non-null  object
 3   ListingCategory (numeric)  83982 non-null  category
 4   BorrowerState              83982 non-null  object
 5   BorrowerAPR                83982 non-null  float64
 6   BorrowerRate               83982 non-null  float64
 7   StatedMonthlyIncome        83982 non-null  float64
 8   ProsperRating (Alpha)      83982 non-null  object
 9   Occupation                 83982 non-null  object
 10  Term                       83982 non-null  int64
 11  EmploymentStatus           83982 non-null  object
 12  TotalInquiries             83982 non-null  int64
 13  DebtToIncomeRatio          83982 non-null  float64
 14  MonthlyLoanPayment         83982 non-null  float64
 15  TotalTrades                83982 non-null  int64
 16  Investors                  83982 non-null  int64
 17  Year                       83982 non-null  object
 18  Month                      83982 non-null  object
 19  Day                        83982 non-null  object
 20  Time                       83982 non-null  object
dtypes: category(1), float64(5), int64(6), object(9)
memory usage: 13.5+ MB